name: Hello world

on:
  push:
    branches:
       - master

jobs:

    hello_world_job:
      steps:
        - name: Set up job
          runs-on: ubuntu-latest
    
      steps:
        - name: Say hello
          run: |
            echo "Hello World!"

      steps:
        - name: Now it is
          run: date

      steps:
        - name: Directory content
          run: ls -l
          
   
  
