name: Deployment pipeline

on:
  push:
    branchs:
      - master

jobs:
  # create virtual environment for pipeline that runs specified OS
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      # checkouts our specific version of code from repository to virual env of the pipeline
      - uses: actions/checkout@v3
      # sets up nodejs and pin the version
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # install application dependencies
      - name: Install dependencies
        run: npm install

      # check styles
      - name: Check styles
        run: npm run eslint 

      # setup e2e testing
      - name: e2e tests
        uses: cypress-io/github-action@v3
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://127.0.0.1:5000
